version: '1.0'

stages:
  - Prepare
  - Build
  - Push
  - Deploy

steps:
  main_clone:
    title: "Clone repository"
    type: git-clone
    stage: Prepare
    description: "Initialize"
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    git: "github"
    revision: ${{CF_BRANCH}}



  build_image:
    title: Build image
    stage: Build
    type: build
    description: Build image
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_SHORT_REVISION}}
    dockerfile: Dockerfile

  init_variables:
    stage: Push
    title: Initializing variables...
    image: alpine
    commands:
      - cf_export CF_REPO_OWNER=`echo $CF_REPO_OWNER | awk '{print tolower($0)}'`

  push_image_commit:
    title: Push image with commit tag
    stage: Push
    type: push
    candidate: ${{build_image}}
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    # registry: ${{CF_REPO_NAME}}
    tags:
    # - "${{CF_SHORT_REVISION}}"
    - "${{CF_REPO_OWNER}}"

  deploy_master:
    title: Deploying to Master
    stage: "Deploy"
    image: 'codefresh/cli:latest'
    environment:
      - STAGE=testing
    commands:
      - codefresh run "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}/deploy-${STAGE}" -b="${{CF_BRANCH}}" -v "CF_RELEASE_TAG=${{CF_SHORT_REVISION}}" -v "CF_SHORT_REVISION=${{CF_SHORT_REVISION}}" -v "CF_COMMIT_URL=${{CF_COMMIT_URL}}" -v "CF_COMMIT_MESSAGE=${CF_COMMIT_MESSAGE}" -v "CF_COMMIT_AUTHOR=${{CF_COMMIT_AUTHOR}}" -v "CF_BRANCH_TAG_NORMALIZED=${{CF_BRANCH_TAG_NORMALIZED}}" -v "STAGE=${STAGE}"
    when:
      branch:
        only:
          - master